# yaml 配置
version: '3'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  web:
    build: .
    ports:
     - "5000:5000"
    links:
      - "db"
    depends_on:
      - "db"

